name: make lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      # Node versions list
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: my-step
        run: make install
        run: make lint

